/* global chrome */
/* JavaScript file Generated by
 * Creativyst(tm) CSV converter
 *   (www.creativyst.com)
 * 
 * (C) Copyright 2002-2003, Creativyst, Inc.
 * 
 * Permission is hereby granted to use,
 * distribute, and change this file for any
 * reason, provided this entire comment remains
 * intact with the work.
 * 
 *
*/

/*JSCPragma:StartCompress
*/

var lsz = 501;

var Col0 = Array([lsz]);

Col0[0] = "URL";

Col0[1] = "facebook.com/";

Col0[2] = "twitter.com/";

Col0[3] = "google.com/";

Col0[4] = "youtube.com/";

Col0[5] = "instagram.com/";

Col0[6] = "linkedin.com/";

Col0[7] = "wordpress.org/";

Col0[8] = "pinterest.com/";

Col0[9] = "wikipedia.org/";

Col0[10] = "wordpress.com/";

Col0[11] = "blogspot.com/";

Col0[12] = "apple.com/";

Col0[13] = "adobe.com/";

Col0[14] = "tumblr.com/";

Col0[15] = "youtu.be/";

Col0[16] = "amazon.com/";

Col0[17] = "goo.gl/";

Col0[18] = "vimeo.com/";

Col0[19] = "flickr.com/";

Col0[20] = "microsoft.com/";

Col0[21] = "yahoo.com/";

Col0[22] = "godaddy.com/";

Col0[23] = "qq.com/";

Col0[24] = "bit.ly/";

Col0[25] = "vk.com/";

Col0[26] = "reddit.com/";

Col0[27] = "w3.org/";

Col0[28] = "baidu.com/";

Col0[29] = "nytimes.com/";

Col0[30] = "t.co/";

Col0[31] = "europa.eu/";

Col0[32] = "buydomains.com/";

Col0[33] = "wp.com/";

Col0[34] = "statcounter.com/";

Col0[35] = "miitbeian.gov.cn/";

Col0[36] = "jimdo.com/";

Col0[37] = "blogger.com/";

Col0[38] = "github.com/";

Col0[39] = "weebly.com/";

Col0[40] = "soundcloud.com/";

Col0[41] = "mozilla.org/";

Col0[42] = "bbc.co.uk/";

Col0[43] = "yandex.ru/";

Col0[44] = "myspace.com/";

Col0[45] = "google.de/";

Col0[46] = "addthis.com/";

Col0[47] = "nih.gov/";

Col0[48] = "theguardian.com/";

Col0[49] = "google.co.jp/";

Col0[50] = "cnn.com/";

Col0[51] = "stumbleupon.com/";

Col0[52] = "gravatar.com/";

Col0[53] = "digg.com/";

Col0[54] = "addtoany.com/";

Col0[55] = "creativecommons.org/";

Col0[56] = "paypal.com/";

Col0[57] = "yelp.com/";

Col0[58] = "imdb.com/";

Col0[59] = "huffingtonpost.com/";

Col0[60] = "feedburner.com/";

Col0[61] = "issuu.com/";

Col0[62] = "wixsite.com/";

Col0[63] = "wix.com/";

Col0[64] = "dropbox.com/";

Col0[65] = "forbes.com/";

Col0[66] = "miibeian.gov.cn/";

Col0[67] = "amazonaws.com/";

Col0[68] = "google.co.uk/";

Col0[69] = "washingtonpost.com/";

Col0[70] = "bluehost.com/";

Col0[71] = "etsy.com/";

Col0[72] = "go.com/";

Col0[73] = "msn.com/";

Col0[74] = "wsj.com/";

Col0[75] = "ameblo.jp/";

Col0[76] = "archive.org/";

Col0[77] = "slideshare.net/";

Col0[78] = "e-recht24.de/";

Col0[79] = "weibo.com/";

Col0[80] = "fc2.com/";

Col0[81] = "eventbrite.com/";

Col0[82] = "parallels.com/";

Col0[83] = "doubleclick.net/";

Col0[84] = "mail.ru/";

Col0[85] = "sourceforge.net/";

Col0[86] = "amazon.co.uk/";

Col0[87] = "telegraph.co.uk/";

Col0[88] = "ebay.com/";

Col0[89] = "amzn.to/";

Col0[90] = "livejournal.com/";

Col0[91] = "51.la/";

Col0[92] = "free.fr/";

Col0[93] = "yahoo.co.jp/";

Col0[94] = "dailymail.co.uk/";

Col0[95] = "reuters.com/";

Col0[96] = "taobao.com/";

Col0[97] = "wikimedia.org/";

Col0[98] = "amazon.de/";

Col0[99] = "typepad.com/";

Col0[100] = "hatena.ne.jp/";

Col0[101] = "bloomberg.com/";

Col0[102] = "elegantthemes.com/";

Col0[103] = "eepurl.com/";

Col0[104] = "usatoday.com/";

Col0[105] = "about.com/";

Col0[106] = "medium.com/";

Col0[107] = "macromedia.com/";

Col0[108] = "xing.com/";

Col0[109] = "bing.com/";

Col0[110] = "time.com/";

Col0[111] = "www.gov.uk/";

Col0[112] = "google.it/";

Col0[113] = "cdc.gov/";

Col0[114] = "tripadvisor.com/";

Col0[115] = "cpanel.net/";

Col0[116] = "amazon.co.jp/";

Col0[117] = "npr.org/";

Col0[118] = "harvard.edu/";

Col0[119] = "bbb.org/";

Col0[120] = "aol.com/";

Col0[121] = "constantcontact.com/";

Col0[122] = "latimes.com/";

Col0[123] = "icio.us/";

Col0[124] = "list-manage.com/";

Col0[125] = "webs.com/";

Col0[126] = "opera.com/";

Col0[127] = "beian.gov.cn/";

Col0[128] = "vkontakte.ru/";

Col0[129] = "blogspot.co.uk/";

Col0[130] = "live.com/";

Col0[131] = "bandcamp.com/";

Col0[132] = "apache.org/";

Col0[133] = "bbc.com/";

Col0[134] = "businessinsider.com/";

Col0[135] = "dailymotion.com/";

Col0[136] = "cpanel.com/";

Col0[137] = "disqus.com/";

Col0[138] = "behance.net/";

Col0[139] = "mit.edu/";

Col0[140] = "rambler.ru/";

Col0[141] = "gnu.org/";

Col0[142] = "sina.com.cn/";

Col0[143] = "spotify.com/";

Col0[144] = "joomla.org/";

Col0[145] = "google.es/";

Col0[146] = "line.me/";

Col0[147] = "wired.com/";

Col0[148] = "github.io/";

Col0[149] = "stanford.edu/";

Col0[150] = "googleusercontent.com/";

Col0[151] = "kickstarter.com/";

Col0[152] = "guardian.co.uk/";

Col0[153] = "imgur.com/";

Col0[154] = "google.fr/";

Col0[155] = "goodreads.com/";

Col0[156] = "nasa.gov/";

Col0[157] = "rakuten.co.jp/";

Col0[158] = "surveymonkey.com/";

Col0[159] = "delicious.com/";

Col0[160] = "independent.co.uk/";

Col0[161] = "whatsapp.com/";

Col0[162] = "one.com/";

Col0[163] = "photobucket.com/";

Col0[164] = "ted.com/";

Col0[165] = "themeforest.net/";

Col0[166] = "homestead.com/";

Col0[167] = "google.ca/";

Col0[168] = "cnet.com/";

Col0[169] = "1und1.de/";

Col0[170] = "deviantart.com/";

Col0[171] = "scribd.com/";

Col0[172] = "jiathis.com/";

Col0[173] = "domainname.de/";

Col0[174] = "ca.gov/";

Col0[175] = "shopify.com/";

Col0[176] = "plesk.com/";

Col0[177] = "wiley.com/";

Col0[178] = "who.int/";

Col0[179] = "un.org/";

Col0[180] = "buzzfeed.com/";

Col0[181] = "theatlantic.com/";

Col0[182] = "barnesandnoble.com/";

Col0[183] = "sakura.ne.jp/";

Col0[184] = "pbs.org/";

Col0[185] = "nationalgeographic.com/";

Col0[186] = "getpocket.com/";

Col0[187] = "blogspot.com.es/";

Col0[188] = "nature.com/";

Col0[189] = "networksolutions.com/";

Col0[190] = "webmd.com/";

Col0[191] = "foxnews.com/";

Col0[192] = "cbsnews.com/";

Col0[193] = "techcrunch.com/";

Col0[194] = "booking.com/";

Col0[195] = "php.net/";

Col0[196] = "berkeley.edu/";

Col0[197] = "cloudfront.net/";

Col0[198] = "sciencedirect.com/";

Col0[199] = "ibm.com/";

Col0[200] = "a8.net/";

Col0[201] = "163.com/";

Col0[202] = "nbcnews.com/";

Col0[203] = "skype.com/";

Col0[204] = "mashable.com/";

Col0[205] = "cornell.edu/";

Col0[206] = "naver.com/";

Col0[207] = "domainretailing.com/";

Col0[208] = "usda.gov/";

Col0[209] = "wp.me/";

Col0[210] = "4.cn/";

Col0[211] = "springer.com/";

Col0[212] = "whitehouse.gov/";

Col0[213] = "squarespace.com/";

Col0[214] = "phoca.cz/";

Col0[215] = "change.org/";

Col0[216] = "cbc.ca/";

Col0[217] = "ft.com/";

Col0[218] = "epa.gov/";

Col0[219] = "secureserver.net/";

Col0[220] = "enable-javascript.com/";

Col0[221] = "meetup.com/";

Col0[222] = "noaa.gov/";

Col0[223] = "cnbc.com/";

Col0[224] = "nps.gov/";

Col0[225] = "phpbb.com/";

Col0[226] = "wikia.com/";

Col0[227] = "usnews.com/";

Col0[228] = "google.nl/";

Col0[229] = "myshopify.com/";

Col0[230] = "mapquest.com/";

Col0[231] = "trustpilot.com/";

Col0[232] = "domainactive.co/";

Col0[233] = "uol.com.br/";

Col0[234] = "foursquare.com/";

Col0[235] = "ow.ly/";

Col0[236] = "google.com.br/";

Col0[237] = "telegram.me/";

Col0[238] = "sohu.com/";

Col0[239] = "loc.gov/";

Col0[240] = "economist.com/";

Col0[241] = "fda.gov/";

Col0[242] = "irs.gov/";

Col0[243] = "themegrill.com/";

Col0[244] = "wufoo.com/";

Col0[245] = "geocities.jp/";

Col0[246] = "bigcartel.com/";

Col0[247] = "livedoor.jp/";

Col0[248] = "chicagotribune.com/";

Col0[249] = "dribbble.com/";

Col0[250] = "hp.com/";

Col0[251] = "doi.org/";

Col0[252] = "prnewswire.com/";

Col0[253] = "ed.gov/";

Col0[254] = "ok.ru/";

Col0[255] = "newyorker.com/";

Col0[256] = "abc.net.au/";

Col0[257] = "bizjournals.com/";

Col0[258] = "slate.com/";

Col0[259] = "houzz.com/";

Col0[260] = "umblr.com/";

Col0[261] = "fb.com/";

Col0[262] = "vice.com/";

Col0[263] = "xinhuanet.com/";

Col0[264] = "engadget.com/";

Col0[265] = "nifty.com/";

Col0[266] = "t.me/";

Col0[267] = "marriott.com/";

Col0[268] = "clickbank.net/";

Col0[269] = "globo.com/";

Col0[270] = "list-manage1.com/";

Col0[271] = "histats.com/";

Col0[272] = "state.gov/";

Col0[273] = "cbslocal.com/";

Col0[274] = "unesco.org/";

Col0[275] = "google.com.au/";

Col0[276] = "umich.edu/";

Col0[277] = "hostnet.nl/";

Col0[278] = "google.pl/";

Col0[279] = "house.gov/";

Col0[280] = "youku.com/";

Col0[281] = "theverge.com/";

Col0[282] = "ocn.ne.jp/";

Col0[283] = "storify.com/";

Col0[284] = "sogou.com/";

Col0[285] = "goo.ne.jp/";

Col0[286] = "fortune.com/";

Col0[287] = "wunderground.com/";

Col0[288] = "aboutcookies.org/";

Col0[289] = "rs6.net/";

Col0[290] = "columbia.edu/";

Col0[291] = "namejet.com/";

Col0[292] = "gofundme.com/";

Col0[293] = "oracle.com/";

Col0[294] = "yale.edu/";

Col0[295] = "psychologytoday.com/";

Col0[296] = "ifeng.com/";

Col0[297] = "washington.edu/";

Col0[298] = "indiatimes.com/";

Col0[299] = "samsung.com/";

Col0[300] = "upenn.edu/";

Col0[301] = "athemes.com/";

Col0[302] = "1and1.com/";

Col0[303] = "studiopress.com/";

Col0[304] = "hilton.com/";

Col0[305] = "debian.org/";

Col0[306] = "wikihow.com/";

Col0[307] = "fbcdn.net/";

Col0[308] = "fb.me/";

Col0[309] = "senate.gov/";

Col0[310] = "fastcompany.com/";

Col0[311] = "mailchimp.com/";

Col0[312] = "alibaba.com/";

Col0[313] = "youronlinechoices.com/";

Col0[314] = "android.com/";

Col0[315] = "researchgate.net/";

Col0[316] = "ustream.tv/";

Col0[317] = "dedecms.com/";

Col0[318] = "zdnet.com/";

Col0[319] = "home.pl/";

Col0[320] = "exblog.jp/";

Col0[321] = "cryoutcreations.eu/";

Col0[322] = "entrepreneur.com/";

Col0[323] = "drupal.org/";

Col0[324] = "sagepub.com/";

Col0[325] = "tripadvisor.co.uk/";

Col0[326] = "businesswire.com/";

Col0[327] = "shinystat.com/";

Col0[328] = "umn.edu/";

Col0[329] = "jugem.jp/";

Col0[330] = "hbr.org/";

Col0[331] = "sciencemag.org/";

Col0[332] = "ftc.gov/";

Col0[333] = "1688.com/";

Col0[334] = "google.co.in/";

Col0[335] = "wisc.edu/";

Col0[336] = "ucla.edu/";

Col0[337] = "inc.com/";

Col0[338] = "psu.edu/";

Col0[339] = "loopia.se/";

Col0[340] = "visma.com/";

Col0[341] = "dreamhost.com/";

Col0[342] = "mijndomein.nl/";

Col0[343] = "loopia.com/";

Col0[344] = "ox.ac.uk/";

Col0[345] = "scientificamerican.com/";

Col0[346] = "utexas.edu/";

Col0[347] = "stackoverflow.com/";

Col0[348] = "1and1.fr/";

Col0[349] = "sedo.com/";

Col0[350] = "mozilla.com/";

Col0[351] = "worldbank.org/";

Col0[352] = "hubspot.com/";

Col0[353] = "census.gov/";

Col0[354] = "arstechnica.com/";

Col0[355] = "mysql.com/";

Col0[356] = "si.edu/";

Col0[357] = "allaboutcookies.org/";

Col0[358] = "usgs.gov/";

Col0[359] = "intel.com/";

Col0[360] = "amazon.fr/";

Col0[361] = "shop-pro.jp/";

Col0[362] = "tandfonline.com/";

Col0[363] = "aliyun.com/";

Col0[364] = "office.com/";

Col0[365] = "alexa.com/";

Col0[366] = "zendesk.com/";

Col0[367] = "nhk.or.jp/";

Col0[368] = "colorlib.com/";

Col0[369] = "accuweather.com/";

Col0[370] = "cisco.com/";

Col0[371] = "google.ru/";

Col0[372] = "cam.ac.uk/";

Col0[373] = "hibu.com/";

Col0[374] = "hollywoodreporter.com/";

Col0[375] = "admin.ch/";

Col0[376] = "example.com/";

Col0[377] = "hhs.gov/";

Col0[378] = "twitch.tv/";

Col0[379] = "networkadvertising.org/";

Col0[380] = "nyu.edu/";

Col0[381] = "teamviewer.com/";

Col0[382] = "nazwa.pl/";

Col0[383] = "variety.com/";

Col0[384] = "netflix.com/";

Col0[385] = "box.com/";

Col0[386] = "prestashop.com/";

Col0[387] = "bls.gov/";

Col0[388] = "bmj.com/";

Col0[389] = "uchicago.edu/";

Col0[390] = "wsimg.com/";

Col0[391] = "www.nhs.uk/";

Col0[392] = "eventbrite.co.uk/";

Col0[393] = "opensource.org/";

Col0[394] = "zenfolio.com/";

Col0[395] = "blogspot.jp/";

Col0[396] = "usc.edu/";

Col0[397] = "va.gov/";

Col0[398] = "cmu.edu/";

Col0[399] = "oecd.org/";

Col0[400] = "ieee.org/";

Col0[401] = "mlb.com/";

Col0[402] = "ename.com.cn/";

Col0[403] = "usa.gov/";

Col0[404] = "steampowered.com/";

Col0[405] = "google.ch/";

Col0[406] = "redcross.org/";

Col0[407] = "bund.de/";

Col0[408] = "thehill.com/";

Col0[409] = "dictionary.com/";

Col0[410] = "360.cn/";

Col0[411] = "hostgator.com/";

Col0[412] = "icann.org/";

Col0[413] = "dot.gov/";

Col0[414] = "adweek.com/";

Col0[415] = "fao.org/";

Col0[416] = "sun.com/";

Col0[417] = "iubenda.com/";

Col0[418] = "gesetze-im-internet.de/";

Col0[419] = "tmall.com/";

Col0[420] = "today.com/";

Col0[421] = "nginx.org/";

Col0[422] = "xiti.com/";

Col0[423] = "venturebeat.com/";

Col0[424] = "snapchat.com/";

Col0[425] = "ietf.org/";

Col0[426] = "symantec.com/";

Col0[427] = "mhlw.go.jp/";

Col0[428] = "duke.edu/";

Col0[429] = "japanpost.jp/";

Col0[430] = "giphy.com/";

Col0[431] = "netscape.com/";

Col0[432] = "justgiving.com/";

Col0[433] = "sec.gov/";

Col0[434] = "illinois.edu/";

Col0[435] = "att.com/";

Col0[436] = "squareup.com/";

Col0[437] = "aboutads.info/";

Col0[438] = "gpo.gov/";

Col0[439] = "tucowsdomains.com/";

Col0[440] = "domainnameshop.com/";

Col0[441] = "plos.org/";

Col0[442] = "elsevier.com/";

Col0[443] = "biomedcentral.com/";

Col0[444] = "reference.com/";

Col0[445] = "oup.com/";

Col0[446] = "ssa.gov/";

Col0[447] = "libsyn.com/";

Col0[448] = "windowsphone.com/";

Col0[449] = "ny.gov/";

Col0[450] = "bigcommerce.com/";

Col0[451] = "oreilly.com/";

Col0[452] = "domeneshop.no/";

Col0[453] = "googleapis.com/";

Col0[454] = "artisteer.com/";

Col0[455] = "arxiv.org/";

Col0[456] = "thenextweb.com/";

Col0[457] = "google.be/";

Col0[458] = "gotowebinar.com/";

Col0[459] = "deloitte.com/";

Col0[460] = "blackberry.com/";

Col0[461] = "w3schools.com/";

Col0[462] = "dol.gov/";

Col0[463] = "python.org/";

Col0[464] = "siteorigin.com/";

Col0[465] = "ewebdevelopment.com/";

Col0[466] = "moz.com/";

Col0[467] = "warnerbros.com/";

Col0[468] = "justice.gov/";

Col0[469] = "quantcast.com/";

Col0[470] = "dhs.gov/";

Col0[471] = "java.com/";

Col0[472] = "fcc.gov/";

Col0[473] = "congress.gov/";

Col0[474] = "g.co/";

Col0[475] = "playstation.com/";

Col0[476] = "iso.org/";

Col0[477] = "opencart.com/";

Col0[478] = "eff.org/";

Col0[479] = "ucl.ac.uk/";

Col0[480] = "moodle.org/";

Col0[481] = "web.de/";

Col0[482] = "unsplash.com/";

Col0[483] = "msdn.com/";

Col0[484] = "nist.gov/";

Col0[485] = "unicef.org/";

Col0[486] = "mlit.go.jp/";

Col0[487] = "canada.ca/";

Col0[488] = "bitbucket.org/";

Col0[489] = "azurewebsites.net/";

Col0[490] = "nginx.com/";

Col0[491] = "dmca.com/";

Col0[492] = "etracker.de/";

Col0[493] = "mynavi.jp/";

Col0[494] = "aarp.org/";

Col0[495] = "gartner.com/";

Col0[496] = "starwoodhotels.com/";

Col0[497] = "typeform.com/";

Col0[498] = "acm.org/";

Col0[499] = "sedoparking.com/";

Col0[500] = "ticketmaster.com/";



window.onload = function() {

/************************HOUR***********************/

    document.querySelector('#hour').addEventListener('click', e => {
      var hour = function () { 
           var i = 0;
	   while (i < 20) {
	         chrome.history.addUrl({url : "https://" + Col0[Math.floor(Math.random() * 500)]});
		 i++;
	   }
      };
      var millisecondsPerHour = 1000 * 60 * 60;
      var oneHourAgo = (new Date()).getTime() - millisecondsPerHour;
      chrome.browsingData.remove({ "since" : oneHourAgo }, { "history" : true }, hour);
    });

/************************DAY***********************/

    document.querySelector('#day').addEventListener('click', e => {
      var day = function () { 
           var i = 0;
	   while (i < 50) {
	         chrome.history.addUrl({url : "https://" + Col0[Math.floor(Math.random() * 500)]});
		 i++;
	   }
      };
      var millisecondsPerDay = 1000 * 60 * 60 * 24;
      var oneDayAgo = (new Date()).getTime() - millisecondsPerDay;
      chrome.browsingData.remove({ "since" : oneDayAgo }, { "history" : true }, day);
    });

/************************WEEK***********************/

    document.querySelector('#week').addEventListener('click', e => {
      var week = function () {
           var i = 0;
	   while (i < 75) {	 
	         chrome.history.addUrl({url : "https://" + Col0[Math.floor(Math.random() * 500)]});
		 i++;
	   }
      };
      var millisecondsPerWeek = 1000 * 60 * 60 * 24 * 7;
      var oneWeekAgo = (new Date()).getTime() - millisecondsPerWeek;
      chrome.browsingData.remove({ "since" : oneWeekAgo }, { "history" : true }, week);
    });

/************************MONTH***********************/

    document.querySelector('#month').addEventListener('click', e => {
      var month = function () {
           var i = 0;
	   while (i < 100) {
	         chrome.history.addUrl({url : "https://" + Col0[Math.floor(Math.random() * 500)]});
		 i++;
	   }
      };
      var millisecondsPerMonth = 1000 * 60 * 60 * 24 * 7 * 30;
      var oneMonthAgo = (new Date()).getTime() - millisecondsPerMonth;
      chrome.browsingData.remove({ "since" : oneMonthAgo }, { "history" : true }, month);
    });

/************************ALL***********************/

    document.querySelector('#all').addEventListener('click', e => {
      var all = function () { 
           var i = 0;
	   while (i < 200) {
	         chrome.history.addUrl({url : "https://" + Col0[Math.floor(Math.random() * 500)]});
		 i++;
	   }
      };
      chrome.history.deleteAll(all);
    });

};
